### ISSUE TITLE
Why using generics in interface definition ?

### ISSUE THREAD

**Issue by sylr** [mus-format/mus-go#7]
Hi,

I'm interested in go-mus but I don't understand the interfaces defined in this package. I've a lot of structs I'd like to encode/decode and it would be much more easier if the interfaces would look like `encoding/json`'s, i.e.:

```go
type Marshaller interface {
	MarshalMUS() (bs []byte, n int, err error)
}

type Unmarshaller interface {
	UnmarshalMUS(bs []byte) (n int, err error)
}

type Sizer interface {
	SizeMUS() (size int)
}

type Skipper interface {
	SkipMUS(bs []byte) (n int, err error)
}
```

Is there something I'm missing that dictates the use of generics ?

Regards.

**Comment by ymz-ncnk** [comment]
If I understood you correctly, you mean that it would be more convenient to implement the Marshal, Unmarshal, and Size methods. However, in this case we would have to deal with pointers (for example, the receiver of the Unmarshal method would have to be a pointer), which mus-go tries not to use for performance reasons.
